version: '3'

services: 
    db:
        container_name: 'db'
        image: mysql:5.7.31
        command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
        restart: always
        ports: 
          - '3308:3306'
        environment: 
            - MYSQL_ROOT_PASSWORD=mysql
            - TZ=America/Sao_Paulo
    #container do app comentado até resolver a conexão entre os dois containers
    # app:
    #     container_name: aplicacao
    #     depends_on:
    #       - db
    #     build: .
    #     command: npm run start
    #     ports:
    #       - '5555:5555'
    #     volumes: 
    #       - .:/usr/app/